/*    ==Paramètres de script==

    Version du serveur source : SQL Server 2016 (13.0.4001)
    Édition du moteur de base de données source : Microsoft SQL Server Enterprise Edition
    Type du moteur de base de données source : SQL Server autonome

    Version du serveur cible : SQL Server 2016
    Édition du moteur de base de données cible : Microsoft SQL Server Enterprise Edition
    Type du moteur de base de données cible : SQL Server autonome
*/

USE [master]
GO

/****** Object:  Database [TennisTableASP]    Script Date: 04/09/2017 04:44:08 ******/
CREATE DATABASE [TennisTableASP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TennisTableASP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TennisTableASP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TennisTableASP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TennisTableASP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TennisTableASP] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TennisTableASP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TennisTableASP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TennisTableASP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TennisTableASP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TennisTableASP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TennisTableASP] SET ARITHABORT OFF 
GO

ALTER DATABASE [TennisTableASP] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TennisTableASP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TennisTableASP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TennisTableASP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TennisTableASP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TennisTableASP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TennisTableASP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TennisTableASP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TennisTableASP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TennisTableASP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TennisTableASP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TennisTableASP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TennisTableASP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TennisTableASP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TennisTableASP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TennisTableASP] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TennisTableASP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TennisTableASP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TennisTableASP] SET  MULTI_USER 
GO

ALTER DATABASE [TennisTableASP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TennisTableASP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TennisTableASP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TennisTableASP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TennisTableASP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TennisTableASP] SET QUERY_STORE = OFF
GO

USE [TennisTableASP]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TennisTableASP] SET  READ_WRITE 
GO

